### PR TITLE
Reviewer updates

### PR DESCRIPTION
**Pull request by gronteix**

### CODE REVIEW

**Comment by gronteix** [comment]
@aaristov here you are!

Sorry, since there were only two small lines of code that were changed (except in the notebooks) I dodn't tag you in the PR.

**Comment by aaristov** [comment]
I've got a problem with the notebook 
image

**Comment by gronteix** [comment]
Stupid ass `{` that was missing grrrr

**Comment by gronteix** [comment]
fixed both branches now

**Comment by aaristov** [comment]
I have a new problem 
image

**Comment by gronteix** [comment]
It's running and working locally on my computer, how is it possible?

**Comment by aaristov** [comment]
could you show the status bar to verify the branch?

**Comment by aaristov** [comment]
mine 
``` 
jupyter lab --version
3.3.2
```

**Comment by gronteix** [comment]
Screenshot 2022-04-11 at 15 05 37

**Comment by aaristov** [comment]
I see, the notebook in the revewer branch is still broken

**Comment by aaristov** [comment]
It works from main

**Comment by aaristov** [comment]
but in main it is missing my changes

**Comment by gronteix** [comment]
to the notebook? Your changes are included in the code though?

**Comment by gronteix** [comment]
ARGH

**Comment by aaristov** [comment]
it depends, some yes, some no

**Pull request merged**
